name: food_bank
description: "Food bank."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  # splash and app icon
  flutter_splash_screen: ^3.0.0
  flutter_launcher_icons: ^0.13.1

  # image
  flutter_svg: ^2.0.10+1

  # State controller
  flutter_bloc: ^8.1.4
  fpdart: ^1.1.0
  get_it: ^7.6.7

  flutter_switch: ^0.3.2

  # Router
  go_router: ^13.2.0

  # Cache storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.3

  #firebase for notifications
  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.21
  device_info_plus: ^10.0.1
  flutter_local_notifications: ^17.0.0
  overlay_support: ^2.1.0

  # others
  internet_connection_checker_plus: ^2.2.0
  percent_indicator: ^4.2.3
  qr_code_scanner: ^1.0.1
  clipboard: ^0.1.3
  pinput: ^3.0.1
  logger: ^2.1.0
  infinite_scroll_pagination: ^4.0.0
  webview_flutter: ^4.3.0
  flutter_tawkto: ^0.0.3
  flutter_dotenv: ^5.1.0

  # Location
  google_places_flutter: ^2.0.8
  geocoding: ^3.0.0
  http: ^1.2.1

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#FFFFFF"
  image: "assets/images/light_logo.png"

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
